import type { SidebarEntry } from "./sidebar";

export const availableTypes: SidebarEntry[] = [
  { text: "Client", link: "/api/client" },
  { text: "Config", link: "/api/config" },
  { text: "Proxy", link: "/api/config#proxy" },
  { text: "LogConfig", link: "/api/config#logconfig" },
  { text: "Context", link: "/api/context" },
  { text: "Update", link: "/api/context#update" },
  { text: "Handler", link: "/guide/handlers#handler-interface" },
  { text: "Filter", link: "/api/filters#filter-type" },
  { text: "HandlerDispatcher", link: "/guide/handlers#handlerdispatcher" },
  { text: "Storage", link: "/api/storage#storage" },
  { text: "PeerStore", link: "/api/storage#peerstore" },
  { text: "MemoryStorage", link: "/api/storage#memorystorage" },
  { text: "SQLiteStorage", link: "/api/storage#sqlitestorage" },
  { text: "PeerEntry", link: "/api/storage#peerentry" },
  { text: "UploadResult", link: "/api/media#uploadresult" },
  { text: "FileChunk", link: "/api/media#filechunk" },
  { text: "SendCodeResult", link: "/api/auth#sendcoderesult" },
  {
    text: "Message & Media",
    collapsed: true,
    items: [
      { text: "Message", link: "/api/types#message" },
      { text: "Media", link: "/api/types#media" },
      { text: "Photo", link: "/api/types#photo" },
      { text: "PhotoSize", link: "/api/types#photosize" },
      { text: "Animation", link: "/api/types#animation" },
      { text: "Audio", link: "/api/types#audio" },
      { text: "Video", link: "/api/types#video" },
      { text: "VideoNote", link: "/api/types#videonote" },
      { text: "Voice", link: "/api/types#voice" },
      { text: "Sticker", link: "/api/types#sticker" },
      { text: "DocumentMedia", link: "/api/types#documentmedia" },
      { text: "Contact", link: "/api/types#contact" },
      { text: "Location", link: "/api/types#location" },
      { text: "Venue", link: "/api/types#venue" },
      { text: "ContactMedia", link: "/api/types#contactmedia" },
      { text: "LocationMedia", link: "/api/types#locationmedia" },
      { text: "VenueMedia", link: "/api/types#venuemedia" },
      { text: "PhotoMedia", link: "/api/types#photomedia" },
      { text: "DiceMedia", link: "/api/types#dicemedia" },
      { text: "GameMedia", link: "/api/types#gamemedia" },
      { text: "InvoiceMedia", link: "/api/types#invoicemedia" },
      { text: "GiveawayMedia", link: "/api/types#giveawaymedia" },
      { text: "GiveawayResultsMedia", link: "/api/types#giveawayresultsmedia" },
      { text: "PollMedia", link: "/api/types#pollmedia" },
      { text: "StoryMedia", link: "/api/types#storymedia" },
      { text: "WebPageMedia", link: "/api/types#webpagemedia" },
      { text: "PaidMedia", link: "/api/types#paidmedia" },
      { text: "PaidMediaInfo", link: "/api/types#paidmediainfo" },
      { text: "PurchasedPaidMedia", link: "/api/types#purchasedpaidmedia" },
      { text: "Thumbnail", link: "/api/types#thumbnail" },
    ],
  },
  {
    text: "Chat & Members",
    collapsed: true,
    items: [
      { text: "Chat", link: "/api/types#chat" },
      { text: "ChatPreview", link: "/api/types#chatpreview" },
      { text: "ChatType", link: "/api/types#chattype" },
      { text: "ChatPhoto", link: "/api/types#chatphoto" },
      { text: "ChatMember", link: "/api/types#chatmember" },
      { text: "ChatMemberStatus", link: "/api/types#chatmemberstatus" },
      { text: "ChatMemberUpdated", link: "/api/types#chatmemberupdated" },
      { text: "ChatMembersFilter", link: "/api/types#chatmembersfilter" },
      { text: "ChatPermissions", link: "/api/types#chatpermissions" },
      { text: "ChatAdminRights", link: "/api/types#chatadminrights" },
      { text: "ChatBannedRights", link: "/api/types#chatbannedrights" },
      { text: "ChatEvent", link: "/api/types#chatevent" },
      { text: "ChatEventAction", link: "/api/types#chateventaction" },
      { text: "ChatEventFilter", link: "/api/types#chateventfilter" },
      { text: "ChatInviteLink", link: "/api/types#chatinvitelink" },
      { text: "ChatInviteLinkJoiner", link: "/api/types#chatinvitelinkjoiner" },
      { text: "ChatJoinRequest", link: "/api/types#chatjoinrequest" },
      { text: "ChatJoinType", link: "/api/types#chatjointype" },
      { text: "ChatBoostUpdated", link: "/api/types#chatboostupdated" },
      { text: "ChatSettings", link: "/api/types#chatsettings" },
      { text: "ChatShared", link: "/api/types#chatshared" },
      { text: "ChatAction", link: "/api/types#chataction" },
      { text: "ChatBackground", link: "/api/types#chatbackground" },
      { text: "Dialog", link: "/api/types#dialog" },
      { text: "Folder", link: "/api/types#folder" },
      { text: "FolderColor", link: "/api/types#foldercolor" },
      { text: "TopChatCategory", link: "/api/types#topchatcategory" },
    ],
  },
  {
    text: "User & Profile",
    collapsed: true,
    items: [
      { text: "User", link: "/api/types#user" },
      { text: "UserStatus", link: "/api/types#userstatus" },
      { text: "UserStatusUpdated", link: "/api/types#userstatusupdated" },
      { text: "UsernameInfo", link: "/api/types#usernameinfo" },
      { text: "UsersShared", link: "/api/types#usersshared" },
      { text: "ProfileColor", link: "/api/types#profilecolor" },
      { text: "ProfileTab", link: "/api/types#profiletab" },
      { text: "EmojiStatus", link: "/api/types#emojistatus" },
      { text: "Birthday", link: "/api/types#birthday" },
      { text: "BusinessConnection", link: "/api/types#businessconnection" },
      { text: "BusinessBotRights", link: "/api/types#businessbotrights" },
      { text: "BusinessIntro", link: "/api/types#businessintro" },
      { text: "BusinessRecipients", link: "/api/types#businessrecipients" },
      { text: "BusinessSchedule", link: "/api/types#businessschedule" },
      { text: "BusinessWeeklyOpen", link: "/api/types#businessweeklyopen" },
      { text: "BusinessWorkingHours", link: "/api/types#businessworkinghours" },
      { text: "ClientPlatform", link: "/api/types#clientplatform" },
      { text: "ActiveSession", link: "/api/types#activesession" },
      { text: "ActiveSessions", link: "/api/types#activesessions" },
    ],
  },
  {
    text: "Messages & Formatting",
    collapsed: true,
    items: [
      { text: "MessageEntity", link: "/api/types#messageentity" },
      { text: "MessageEntityType", link: "/api/types#messageentitytype" },
      { text: "MessageOrigin", link: "/api/types#messageorigin" },
      { text: "MessageOriginType", link: "/api/types#messageorigintype" },
      { text: "MessageMediaType", link: "/api/types#messagemediatype" },
      { text: "MessageServiceType", link: "/api/types#messageservicetype" },
      { text: "MessageReactions", link: "/api/types#messagereactions" },
      { text: "MessageReactionUpdated", link: "/api/types#messagereactionupdated" },
      { text: "MessageReactionCountUpdated", link: "/api/types#messagereactioncountupdated" },
      { text: "FormattedText", link: "/api/types#formattedtext" },
      { text: "ParseMode", link: "/api/types#parsemode" },
      { text: "TextQuote", link: "/api/types#textquote" },
      { text: "FactCheck", link: "/api/types#factcheck" },
      { text: "LinkPreviewOptions", link: "/api/types#linkpreviewoptions" },
      { text: "ForwardHeader", link: "/api/types#forwardheader" },
      { text: "ExternalReplyInfo", link: "/api/types#externalreplyinfo" },
      { text: "ReplyParameters", link: "/api/types#replyparameters" },
      { text: "ReplyColor", link: "/api/types#replycolor" },
      { text: "DeletedMessages", link: "/api/types#deletedmessages" },
      { text: "MessagesFilter", link: "/api/types#messagesfilter" },
    ],
  },
  {
    text: "Reactions & Polls",
    collapsed: true,
    items: [
      { text: "Reaction", link: "/api/types#reaction" },
      { text: "ReactionCount", link: "/api/types#reactioncount" },
      { text: "BotReactionCount", link: "/api/types#botreactioncount" },
      { text: "PaidReactionPrivacy", link: "/api/types#paidreactionprivacy" },
      { text: "PaidReactor", link: "/api/types#paidreactor" },
      { text: "PollType", link: "/api/types#polltype" },
      { text: "PollUpdate", link: "/api/types#pollupdate" },
      { text: "PollAnswer", link: "/api/types#pollanswer" },
    ],
  },
  {
    text: "Keyboards & Buttons",
    collapsed: true,
    items: [
      { text: "ReplyMarkup", link: "/api/types#replymarkup" },
      { text: "ReplyMarkupType", link: "/api/types#replymarkuptype" },
      { text: "InlineKeyboardButton", link: "/api/types#inlinekeyboardbutton" },
      { text: "KeyboardButton", link: "/api/types#keyboardbutton" },
      { text: "Button", link: "/api/types#button" },
      { text: "ButtonType", link: "/api/types#buttontype" },
      { text: "ButtonStyle", link: "/api/types#buttonstyle" },
      { text: "ForceReply", link: "/api/types#forcereply" },
      { text: "ReplyKeyboardRemove", link: "/api/types#replykeyboardremove" },
      { text: "LoginURL", link: "/api/types#loginurl" },
      { text: "KeyboardButtonPollType", link: "/api/types#keyboardbuttonpolltype" },
      { text: "KeyboardButtonRequestChat", link: "/api/types#keyboardbuttonrequestchat" },
      { text: "KeyboardButtonRequestUsers", link: "/api/types#keyboardbuttonrequestusers" },
    ],
  },
  {
    text: "Inline & Callbacks",
    collapsed: true,
    items: [
      { text: "CallbackQuery", link: "/api/types#callbackquery" },
      { text: "InlineQuery", link: "/api/types#inlinequery" },
      { text: "InlineQueryResult", link: "/api/types#inlinequeryresult" },
      { text: "ChosenInlineResult", link: "/api/types#choseninlineresult" },
      { text: "InputMessageContent", link: "/api/types#inputmessagecontent" },
      { text: "InputContentType", link: "/api/types#inputcontenttype" },
      { text: "SentWebAppMessage", link: "/api/types#sentwebappmessage" },
      { text: "WebAppData", link: "/api/types#webappdata" },
      { text: "WebAppInfo", link: "/api/types#webappinfo" },
    ],
  },
  {
    text: "Payments & Shipping",
    collapsed: true,
    items: [
      { text: "Payment", link: "/api/types#payment" },
      { text: "PaymentFormType", link: "/api/types#paymentformtype" },
      { text: "PaymentQueries", link: "/api/types#paymentqueries" },
      { text: "Invoice", link: "/api/types#invoice" },
      { text: "InvoiceType", link: "/api/types#invoicetype" },
      { text: "LabeledPrice", link: "/api/types#labeledprice" },
      { text: "ShippingAddress", link: "/api/types#shippingaddress" },
      { text: "ShippingOption", link: "/api/types#shippingoption" },
      { text: "ShippingQuery", link: "/api/types#shippingquery" },
      { text: "OrderInfo", link: "/api/types#orderinfo" },
      { text: "PreCheckoutQuery", link: "/api/types#precheckoutquery" },
      { text: "SuccessfulPayment", link: "/api/types#successfulpayment" },
      { text: "InputCredentials", link: "/api/types#inputcredentials" },
      { text: "InputInvoice", link: "/api/types#inputinvoice" },
      { text: "CredentialsType", link: "/api/types#credentialstype" },
    ],
  },
  {
    text: "Stories",
    collapsed: true,
    items: [
      { text: "Story", link: "/api/types#story" },
      { text: "StoryView", link: "/api/types#storyview" },
      { text: "StoriesPrivacyRules", link: "/api/types#storiesprivacyrules" },
    ],
  },
  {
    text: "Gifts & Giveaways",
    collapsed: true,
    items: [
      { text: "GiftType", link: "/api/types#gifttype" },
      { text: "GiftAttributeType", link: "/api/types#giftattributetype" },
      { text: "GiftUpgradePreview", link: "/api/types#giftupgradepreview" },
      { text: "GiftUpgradePrice", link: "/api/types#giftupgradeprice" },
      { text: "GiftedPremium", link: "/api/types#giftedpremium" },
      { text: "GiftedStars", link: "/api/types#giftedstars" },
      { text: "GiftAuction", link: "/api/types#giftauction" },
      { text: "GiftCollection", link: "/api/types#giftcollection" },
      { text: "GiftForResaleOrder", link: "/api/types#giftforresaleorder" },
      { text: "GiftPurchaseLimit", link: "/api/types#giftpurchaselimit" },
      { text: "GiftPurchaseOfferState", link: "/api/types#giftpurchaseofferstate" },
      { text: "UpgradedGiftAttribute", link: "/api/types#upgradedgiftattribute" },
      { text: "UpgradedGiftOrigin", link: "/api/types#upgradedgiftorigin" },
      { text: "UpgradedGiftOriginalDetails", link: "/api/types#upgradedgiftoriginaldetails" },
      { text: "UpgradedGiftPurchaseOffer", link: "/api/types#upgradedgiftpurchaseoffer" },
      { text: "UpgradedGiftValueInfo", link: "/api/types#upgradedgiftvalueinfo" },
      { text: "CheckedGiftCode", link: "/api/types#checkedgiftcode" },
      { text: "PremiumGiftCode", link: "/api/types#premiumgiftcode" },
      { text: "Giveaway", link: "/api/types#giveaway" },
      { text: "GiveawayWinners", link: "/api/types#giveawaywinners" },
      { text: "BoostInfo", link: "/api/types#boostinfo" },
      { text: "BoostsStatus", link: "/api/types#boostsstatus" },
      { text: "MyBoost", link: "/api/types#myboost" },
    ],
  },
  {
    text: "Privacy & Security",
    collapsed: true,
    items: [
      { text: "PrivacyKey", link: "/api/types#privacykey" },
      { text: "PrivacyRule", link: "/api/types#privacyrule" },
      { text: "PrivacyRuleType", link: "/api/types#privacyruletype" },
      { text: "InputPrivacyRule", link: "/api/types#inputprivacyrule" },
      { text: "InputPrivacyRuleType", link: "/api/types#inputprivacyruletype" },
      { text: "GlobalPrivacySettings", link: "/api/types#globalprivacysettings" },
      { text: "BlockList", link: "/api/types#blocklist" },
    ],
  },
  {
    text: "Auth & Sessions",
    collapsed: true,
    items: [
      { text: "SentCodeInfo", link: "/api/types#sentcodeinfo" },
      { text: "SentCodeType", link: "/api/types#sentcodetype" },
      { text: "NextCodeType", link: "/api/types#nextcodetype" },
      { text: "TermsOfService", link: "/api/types#termsofservice" },
      { text: "PhoneNumberCodeType", link: "/api/types#phonenumbercodetype" },
    ],
  },
  {
    text: "Input Types & Helpers",
    collapsed: true,
    items: [
      { text: "InputMedia", link: "/api/types#inputmedia" },
      { text: "InputMediaType", link: "/api/types#inputmediatype" },
      { text: "InputChatPhoto", link: "/api/types#inputchatphoto" },
      { text: "InputPhoto", link: "/api/types#inputphoto" },
      { text: "InputPollOption", link: "/api/types#inputpolloption" },
      { text: "InputPhoneContact", link: "/api/types#inputphonecontact" },
      { text: "MaskPosition", link: "/api/types#maskposition" },
      { text: "MaskPointType", link: "/api/types#maskpointtype" },
      { text: "StickerType", link: "/api/types#stickertype" },
      { text: "MediaArea", link: "/api/types#mediaarea" },
      { text: "MediaAreaType", link: "/api/types#mediaareatype" },
      { text: "PeerInfo", link: "/api/types#peerinfo" },
      { text: "PeerMap", link: "/api/types#peermap" },
    ],
  },
  {
    text: "Bot & Commands",
    collapsed: true,
    items: [
      { text: "BotCommand", link: "/api/types#botcommand" },
      { text: "BotCommandScope", link: "/api/types#botcommandscope" },
      { text: "BotCommandScopeType", link: "/api/types#botcommandscopetype" },
      { text: "MenuButton", link: "/api/types#menubutton" },
      { text: "MenuButtonType", link: "/api/types#menubuttontype" },
      { text: "ManagedBotUpdated", link: "/api/types#managedbotupdated" },
    ],
  },
  {
    text: "Service & System",
    collapsed: true,
    items: [
      { text: "ServiceMessage", link: "/api/types#servicemessage" },
      { text: "ServiceActionType", link: "/api/types#serviceactiontype" },
      { text: "PhoneCallDiscardReason", link: "/api/types#phonecalldiscardreason" },
      { text: "PhoneCallEnded", link: "/api/types#phonecallended" },
      { text: "PhoneCallStarted", link: "/api/types#phonecallstarted" },
      { text: "ProximityAlertTriggered", link: "/api/types#proximityalerttriggered" },
      { text: "VideoChatStarted", link: "/api/types#videochatstarted" },
      { text: "VideoChatEnded", link: "/api/types#videochatoended" },
      { text: "VideoChatScheduled", link: "/api/types#videochatscheduled" },
      { text: "VideoChatMembersInvited", link: "/api/types#videochatmembersinvited" },
      { text: "GroupCallMember", link: "/api/types#groupcallmember" },
      { text: "WriteAccessAllowed", link: "/api/types#writeaccessallowed" },
      { text: "GameHighScore", link: "/api/types#gamehighscore" },
      { text: "AvailableEffect", link: "/api/types#availableeffect" },
      { text: "ChatColor", link: "/api/types#chatcolor" },
      { text: "Restriction", link: "/api/types#restriction" },
      { text: "Settings", link: "/api/types#settings" },
      { text: "TranslatorFunc", link: "/api/types#translatorfunc" },
    ],
  },
  {
    text: "Forum & Topics",
    collapsed: true,
    items: [
      { text: "ForumTopic", link: "/api/types#forumtopic" },
      { text: "ForumTopicCreated", link: "/api/types#forumtopiccreated" },
      { text: "ForumTopicEdited", link: "/api/types#forumtopicedited" },
    ],
  },
  {
    text: "Checklists & Suggested Posts",
    collapsed: true,
    items: [
      { text: "Checklist", link: "/api/types#checklist" },
      { text: "ChecklistTask", link: "/api/types#checklisttask" },
      { text: "SuggestedPostParameters", link: "/api/types#suggestedpostparameters" },
      { text: "SuggestedPostPrice", link: "/api/types#suggestedpostprice" },
      { text: "SuggestedPostState", link: "/api/types#suggestedpoststate" },
      { text: "SuggestedPostRefundReason", link: "/api/types#suggestedpostrefundreason" },
    ],
  },
  {
    text: "Params",
    collapsed: true,
    items: [
      { text: "SendMessage", link: "/api/types#sendmessage-params" },
      { text: "EditMessage", link: "/api/types#editmessage-params" },
      { text: "CopyMessage", link: "/api/types#copymessage-params" },
      { text: "ForwardMessages", link: "/api/types#forwardmessages-params" },
      { text: "DeleteMessages", link: "/api/types#deletemessages-params" },
      { text: "PinMessage", link: "/api/types#pinmessage-params" },
      { text: "Download", link: "/api/types#download-params" },
      { text: "InlineQuery", link: "/api/types#inlinequery-params" },
      { text: "ParseMode", link: "/api/types#parsemode-params" },
      { text: "ProgressFunc", link: "/api/types#progressfunc" },
      { text: "ProgressInfo", link: "/api/types#progressinfo" },
    ],
  },
  {
    text: "Binder Interfaces",
    collapsed: true,
    items: [
      { text: "Binder", link: "/api/types#binder" },
      { text: "ChatBinder", link: "/api/types#chatbinder" },
    ],
  },
];
