export interface SidebarEntry {
  text: string;
  link?: string;
  collapsed?: boolean;
  items?: SidebarEntry[];
}

export { availableTypes } from "./sidebar-types";
export {
  messageMethods,
  callbackMethods,
  inlineMethods,
  chatMethods,
  userBoundMethods,
  storyBoundMethods,
  giftBoundMethods,
  otherBoundMethods,
} from "./sidebar-bound";

export const availableMethods: SidebarEntry[] = [
  { text: "Connect", link: "/api/client#connect" },
  { text: "Start", link: "/api/client#start" },
  { text: "Stop", link: "/api/client#stop" },
  { text: "Idle", link: "/api/client#idle" },
  { text: "Disconnect", link: "/api/client#disconnect" },
  { text: "IsConnected", link: "/api/client#isconnected" },
  { text: "Invoke", link: "/api/client#invoke" },
  { text: "InvokeRaw", link: "/api/client#invokeraw" },
  { text: "HandleUpdates", link: "/api/client#handleupdates" },
  { text: "ResolvePeer", link: "/api/client#resolvepeer" },
  { text: "GetSession", link: "/api/client#getsession" },
  { text: "ExportSessionString", link: "/api/client#exportsessionstring" },
  { text: "LogOut", link: "/api/client#logout" },
  { text: "SendMessage", link: "/api/messages#sendmessage" },
  { text: "SendMedia", link: "/api/messages#sendmedia" },
  { text: "SendContact", link: "/api/messages#sendcontact" },
  { text: "SendLocation", link: "/api/messages#sendlocation" },
  { text: "SendVenue", link: "/api/messages#sendvenue" },
  { text: "SendDice", link: "/api/messages#senddice" },
  { text: "SendPoll", link: "/api/messages#sendpoll" },
  { text: "SendGame", link: "/api/messages#sendgame" },
  { text: "SendMediaGroup", link: "/api/messages#sendmediagroup" },
  { text: "SendChatAction", link: "/api/messages#sendchataction" },
  { text: "ForwardMessages", link: "/api/messages#forwardmessages" },
  { text: "ForwardMediaGroup", link: "/api/messages#forwardmediagroup" },
  { text: "DeleteMessages", link: "/api/messages#deletemessages" },
  { text: "DeleteChatHistory", link: "/api/messages#deletechathistory" },
  { text: "GetChatHistory", link: "/api/messages#getchathistory" },
  { text: "GetMessages", link: "/api/messages#getmessages" },
  { text: "EditMessageText", link: "/api/messages#editmessagetext" },
  { text: "EditMessageCaption", link: "/api/messages#editmessagecaption" },
  { text: "EditMessageMedia", link: "/api/messages#editmessagemedia" },
  { text: "EditMessageReplyMarkup", link: "/api/messages#editmessagereplymarkup" },
  { text: "CopyMessage", link: "/api/messages#copymessage" },
  { text: "CopyMediaGroup", link: "/api/messages#copymediagroup" },
  { text: "PinMessage", link: "/api/messages#pinmessage" },
  { text: "UnpinMessage", link: "/api/messages#unpinmessage" },
  { text: "UnpinAllMessages", link: "/api/messages#unpinallmessages" },
  { text: "ReadHistory", link: "/api/messages#readhistory" },
  { text: "ReadMentions", link: "/api/messages#readmentions" },
  { text: "ReadReactions", link: "/api/messages#readreactions" },
  { text: "SendReaction", link: "/api/messages#sendreaction" },
  { text: "SendPaidReaction", link: "/api/messages#sendpaidreaction" },
  { text: "VotePoll", link: "/api/messages#votepoll" },
  { text: "StopPoll", link: "/api/messages#stoppoll" },
  { text: "RetractVote", link: "/api/messages#retractvote" },
  { text: "SearchMessages", link: "/api/messages#searchmessages" },
  { text: "SearchGlobal", link: "/api/messages#searchglobal" },
  { text: "SearchMessagesCount", link: "/api/messages#searchmessagescount" },
  { text: "SearchGlobalCount", link: "/api/messages#searchglobalcount" },
  { text: "UploadFile", link: "/api/media#uploadfile" },
  { text: "UploadFromReader", link: "/api/media#uploadfromreader" },
  { text: "UploadFromFile", link: "/api/media#uploadfromfile" },
  { text: "DownloadFile", link: "/api/media#downloadfile" },
  { text: "DownloadToFile", link: "/api/media#downloadtofile" },
  { text: "DownloadMedia", link: "/api/media#downloadmedia" },
  { text: "StreamFile", link: "/api/media#streamfile" },
  { text: "GetFileLocation", link: "/api/media#getfilelocation" },
  { text: "SendCode", link: "/api/auth#sendcode" },
  { text: "SignIn", link: "/api/auth#signin" },
  { text: "SignUp", link: "/api/auth#signup" },
  { text: "CheckPassword", link: "/api/auth#checkpassword" },
  { text: "ExportLoginToken", link: "/api/auth#exportlogintoken" },
  { text: "ImportLoginToken", link: "/api/auth#importlogintoken" },
  { text: "GetMe", link: "/api/auth#getme" },
  { text: "AnswerCallbackQuery", link: "/api/client#answercallbackquery" },
  { text: "AnswerInlineQuery", link: "/api/client#answerinlinequery" },
  { text: "GetInlineBotResults", link: "/api/client#getinlinebotresults" },
  { text: "SendInlineBotResult", link: "/api/client#sendinlinebotresult" },
  { text: "ArchiveChat", link: "/api/client#archivechat" },
  { text: "UnarchiveChat", link: "/api/client#unarchivechat" },
  { text: "SetChatTitle", link: "/api/client#setchattitle" },
  { text: "SetChatDescription", link: "/api/client#setchatdescription" },
  { text: "SetChatPhoto", link: "/api/client#setchatphoto" },
  { text: "DeleteChatPhoto", link: "/api/client#deletechatphoto" },
  { text: "SetChatUsername", link: "/api/client#setchatusername" },
  { text: "JoinChat", link: "/api/client#joinchat" },
  { text: "LeaveChat", link: "/api/client#leavechat" },
  { text: "GetChat", link: "/api/client#getchat" },
  { text: "GetChatMember", link: "/api/client#getchatmember" },
  { text: "GetChatMembers", link: "/api/client#getchatmembers" },
  { text: "BanChatMember", link: "/api/client#banchatmember" },
  { text: "UnbanChatMember", link: "/api/client#unbanchatmember" },
  { text: "RestrictChatMember", link: "/api/client#restrictchatmember" },
  { text: "PromoteChatMember", link: "/api/client#promotechatmember" },
  { text: "ExportChatInviteLink", link: "/api/client#exportchatinvitelink" },
  { text: "AddChatMember", link: "/api/client#addchatmember" },
  { text: "MarkChatUnread", link: "/api/client#markchatunread" },
  { text: "SetProtectedContent", link: "/api/client#setprotectedcontent" },
  { text: "SetChatTTL", link: "/api/client#setchatttl" },
  { text: "SetChatPermissions", link: "/api/client#setchatpermissions" },
  { text: "SetAdministratorTitle", link: "/api/client#setadministratortitle" },
  { text: "SetSlowMode", link: "/api/client#setslowmode" },
  { text: "MuteChat", link: "/api/client#mutechat" },
  { text: "UnmuteChat", link: "/api/client#unmutechat" },
  { text: "BlockUser", link: "/api/client#blockuser" },
  { text: "UnblockUser", link: "/api/client#unblockuser" },
  { text: "GetChatEventLog", link: "/api/client#getchateventlog" },
];

export const userMethods: SidebarEntry[] = [
  { text: "GetMe", link: "/api/users#getme" },
  { text: "GetUser", link: "/api/users#getuser" },
  { text: "GetUsers", link: "/api/users#getusers" },
  { text: "GetCommonChats", link: "/api/users#getcommonchats" },
  { text: "UpdateProfile", link: "/api/users#updateprofile" },
  { text: "SetProfilePhoto", link: "/api/users#setprofilephoto" },
  { text: "DeleteProfilePhoto", link: "/api/users#deleteprofilephoto" },
  { text: "GetProfilePhotos", link: "/api/users#getprofilephotos" },
  { text: "SetUsername", link: "/api/users#setusername" },
  { text: "SetBio", link: "/api/users#setbio" },
  { text: "BlockUser", link: "/api/users#blockuser" },
  { text: "UnblockUser", link: "/api/users#unblockuser" },
  { text: "GetBlocked", link: "/api/users#getblocked" },
  { text: "AddContact", link: "/api/users#addcontact" },
  { text: "DeleteContacts", link: "/api/users#deletecontacts" },
  { text: "GetContacts", link: "/api/users#getcontacts" },
];
