export interface SidebarEntry {
  text: string;
  link?: string;
  collapsed?: boolean;
  items?: SidebarEntry[];
}

export const availableMethods: SidebarEntry[] = [
  { text: "Connect", link: "/api/client#connect" },
  { text: "Start", link: "/api/client#start" },
  { text: "Stop", link: "/api/client#stop" },
  { text: "Idle", link: "/api/client#idle" },
  { text: "Disconnect", link: "/api/client#disconnect" },
  { text: "IsConnected", link: "/api/client#isconnected" },
  { text: "Invoke", link: "/api/client#invoke" },
  { text: "InvokeRaw", link: "/api/client#invokeraw" },
  { text: "HandleUpdates", link: "/api/client#handleupdates" },
  { text: "ResolvePeer", link: "/api/client#resolvepeer" },
  { text: "GetSession", link: "/api/client#getsession" },
  { text: "ExportSessionString", link: "/api/client#exportsessionstring" },
  { text: "LogOut", link: "/api/client#logout" },
  { text: "SendMessage", link: "/api/messages#sendmessage" },
  { text: "SendMedia", link: "/api/messages#sendmedia" },
  { text: "SendContact", link: "/api/messages#sendcontact" },
  { text: "SendLocation", link: "/api/messages#sendlocation" },
  { text: "SendVenue", link: "/api/messages#sendvenue" },
  { text: "SendDice", link: "/api/messages#senddice" },
  { text: "SendPoll", link: "/api/messages#sendpoll" },
  { text: "SendGame", link: "/api/messages#sendgame" },
  { text: "SendMediaGroup", link: "/api/messages#sendmediagroup" },
  { text: "SendChatAction", link: "/api/messages#sendchataction" },
  { text: "ForwardMessages", link: "/api/messages#forwardmessages" },
  { text: "ForwardMediaGroup", link: "/api/messages#forwardmediagroup" },
  { text: "DeleteMessages", link: "/api/messages#deletemessages" },
  { text: "DeleteChatHistory", link: "/api/messages#deletechathistory" },
  { text: "GetChatHistory", link: "/api/messages#getchathistory" },
  { text: "GetMessages", link: "/api/messages#getmessages" },
  { text: "EditMessageText", link: "/api/messages#editmessagetext" },
  { text: "EditMessageCaption", link: "/api/messages#editmessagecaption" },
  { text: "EditMessageMedia", link: "/api/messages#editmessagemedia" },
  { text: "EditMessageReplyMarkup", link: "/api/messages#editmessagereplymarkup" },
  { text: "CopyMessage", link: "/api/messages#copymessage" },
  { text: "CopyMediaGroup", link: "/api/messages#copymediagroup" },
  { text: "PinMessage", link: "/api/messages#pinmessage" },
  { text: "UnpinMessage", link: "/api/messages#unpinmessage" },
  { text: "UnpinAllMessages", link: "/api/messages#unpinallmessages" },
  { text: "ReadHistory", link: "/api/messages#readhistory" },
  { text: "ReadMentions", link: "/api/messages#readmentions" },
  { text: "ReadReactions", link: "/api/messages#readreactions" },
  { text: "SendReaction", link: "/api/messages#sendreaction" },
  { text: "SendPaidReaction", link: "/api/messages#sendpaidreaction" },
  { text: "VotePoll", link: "/api/messages#votepoll" },
  { text: "StopPoll", link: "/api/messages#stoppoll" },
  { text: "RetractVote", link: "/api/messages#retractvote" },
  { text: "SearchMessages", link: "/api/messages#searchmessages" },
  { text: "SearchGlobal", link: "/api/messages#searchglobal" },
  { text: "SearchMessagesCount", link: "/api/messages#searchmessagescount" },
  { text: "SearchGlobalCount", link: "/api/messages#searchglobalcount" },
  { text: "UploadFile", link: "/api/media#uploadfile" },
  { text: "UploadFromReader", link: "/api/media#uploadfromreader" },
  { text: "UploadFromFile", link: "/api/media#uploadfromfile" },
  { text: "DownloadFile", link: "/api/media#downloadfile" },
  { text: "DownloadToFile", link: "/api/media#downloadtofile" },
  { text: "DownloadMedia", link: "/api/media#downloadmedia" },
  { text: "StreamFile", link: "/api/media#streamfile" },
  { text: "GetFileLocation", link: "/api/media#getfilelocation" },
  { text: "SendCode", link: "/api/auth#sendcode" },
  { text: "SignIn", link: "/api/auth#signin" },
  { text: "SignUp", link: "/api/auth#signup" },
  { text: "CheckPassword", link: "/api/auth#checkpassword" },
  { text: "ExportLoginToken", link: "/api/auth#exportlogintoken" },
  { text: "ImportLoginToken", link: "/api/auth#importlogintoken" },
  { text: "GetMe", link: "/api/auth#getme" },
  { text: "AnswerCallbackQuery", link: "/api/client#answercallbackquery" },
  { text: "AnswerInlineQuery", link: "/api/client#answerinlinequery" },
  { text: "GetInlineBotResults", link: "/api/client#getinlinebotresults" },
  { text: "SendInlineBotResult", link: "/api/client#sendinlinebotresult" },
  { text: "ArchiveChat", link: "/api/client#archivechat" },
  { text: "UnarchiveChat", link: "/api/client#unarchivechat" },
  { text: "SetChatTitle", link: "/api/client#setchattitle" },
  { text: "SetChatDescription", link: "/api/client#setchatdescription" },
  { text: "SetChatPhoto", link: "/api/client#setchatphoto" },
  { text: "DeleteChatPhoto", link: "/api/client#deletechatphoto" },
  { text: "SetChatUsername", link: "/api/client#setchatusername" },
  { text: "JoinChat", link: "/api/client#joinchat" },
  { text: "LeaveChat", link: "/api/client#leavechat" },
  { text: "GetChat", link: "/api/client#getchat" },
  { text: "GetChatMember", link: "/api/client#getchatmember" },
  { text: "GetChatMembers", link: "/api/client#getchatmembers" },
  { text: "BanChatMember", link: "/api/client#banchatmember" },
  { text: "UnbanChatMember", link: "/api/client#unbanchatmember" },
  { text: "RestrictChatMember", link: "/api/client#restrictchatmember" },
  { text: "PromoteChatMember", link: "/api/client#promotechatmember" },
  { text: "ExportChatInviteLink", link: "/api/client#exportchatinvitelink" },
  { text: "AddChatMember", link: "/api/client#addchatmember" },
  { text: "MarkChatUnread", link: "/api/client#markchatunread" },
  { text: "SetProtectedContent", link: "/api/client#setprotectedcontent" },
  { text: "SetChatTTL", link: "/api/client#setchatttl" },
  { text: "SetChatPermissions", link: "/api/client#setchatpermissions" },
  { text: "SetAdministratorTitle", link: "/api/client#setadministratortitle" },
  { text: "SetSlowMode", link: "/api/client#setslowmode" },
  { text: "MuteChat", link: "/api/client#mutechat" },
  { text: "UnmuteChat", link: "/api/client#unmutechat" },
  { text: "BlockUser", link: "/api/client#blockuser" },
  { text: "UnblockUser", link: "/api/client#unblockuser" },
  { text: "GetChatEventLog", link: "/api/client#getchateventlog" },
];

export const availableTypes: SidebarEntry[] = [
  { text: "Client", link: "/api/client" },
  { text: "Config", link: "/api/config" },
  { text: "Proxy", link: "/api/config#proxy" },
  { text: "LogConfig", link: "/api/config#logconfig" },
  { text: "Context", link: "/api/context" },
  { text: "Update", link: "/api/context#update" },
  { text: "Handler", link: "/guide/handlers#handler-interface" },
  { text: "Filter", link: "/api/filters#filter-type" },
  { text: "HandlerDispatcher", link: "/guide/handlers#handlerdispatcher" },
  { text: "Storage", link: "/api/storage#storage" },
  { text: "PeerStore", link: "/api/storage#peerstore" },
  { text: "MemoryStorage", link: "/api/storage#memorystorage" },
  { text: "SQLiteStorage", link: "/api/storage#sqlitestorage" },
  { text: "PeerEntry", link: "/api/storage#peerentry" },
  { text: "UploadResult", link: "/api/media#uploadresult" },
  { text: "FileChunk", link: "/api/media#filechunk" },
  { text: "SendCodeResult", link: "/api/auth#sendcoderesult" },
  {
    text: "Message & Media",
    collapsed: true,
    items: [
      { text: "Message", link: "/api/types#message" },
      { text: "Media", link: "/api/types#media" },
      { text: "Photo", link: "/api/types#photo" },
      { text: "PhotoSize", link: "/api/types#photosize" },
      { text: "Animation", link: "/api/types#animation" },
      { text: "Audio", link: "/api/types#audio" },
      { text: "Video", link: "/api/types#video" },
      { text: "VideoNote", link: "/api/types#videonote" },
      { text: "Voice", link: "/api/types#voice" },
      { text: "Sticker", link: "/api/types#sticker" },
      { text: "DocumentMedia", link: "/api/types#documentmedia" },
      { text: "Contact", link: "/api/types#contact" },
      { text: "Location", link: "/api/types#location" },
      { text: "Venue", link: "/api/types#venue" },
      { text: "ContactMedia", link: "/api/types#contactmedia" },
      { text: "LocationMedia", link: "/api/types#locationmedia" },
      { text: "VenueMedia", link: "/api/types#venuemedia" },
      { text: "PhotoMedia", link: "/api/types#photomedia" },
      { text: "DiceMedia", link: "/api/types#dicemedia" },
      { text: "GameMedia", link: "/api/types#gamemedia" },
      { text: "InvoiceMedia", link: "/api/types#invoicemedia" },
      { text: "GiveawayMedia", link: "/api/types#giveawaymedia" },
      { text: "GiveawayResultsMedia", link: "/api/types#giveawayresultsmedia" },
      { text: "PollMedia", link: "/api/types#pollmedia" },
      { text: "StoryMedia", link: "/api/types#storymedia" },
      { text: "WebPageMedia", link: "/api/types#webpagemedia" },
      { text: "PaidMedia", link: "/api/types#paidmedia" },
      { text: "PaidMediaInfo", link: "/api/types#paidmediainfo" },
      { text: "PurchasedPaidMedia", link: "/api/types#purchasedpaidmedia" },
      { text: "Thumbnail", link: "/api/types#thumbnail" },
    ],
  },
  {
    text: "Chat & Members",
    collapsed: true,
    items: [
      { text: "Chat", link: "/api/types#chat" },
      { text: "ChatPreview", link: "/api/types#chatpreview" },
      { text: "ChatType", link: "/api/types#chattype" },
      { text: "ChatPhoto", link: "/api/types#chatphoto" },
      { text: "ChatMember", link: "/api/types#chatmember" },
      { text: "ChatMemberStatus", link: "/api/types#chatmemberstatus" },
      { text: "ChatMemberUpdated", link: "/api/types#chatmemberupdated" },
      { text: "ChatMembersFilter", link: "/api/types#chatmembersfilter" },
      { text: "ChatPermissions", link: "/api/types#chatpermissions" },
      { text: "ChatAdminRights", link: "/api/types#chatadminrights" },
      { text: "ChatBannedRights", link: "/api/types#chatbannedrights" },
      { text: "ChatEvent", link: "/api/types#chatevent" },
      { text: "ChatEventAction", link: "/api/types#chateventaction" },
      { text: "ChatEventFilter", link: "/api/types#chateventfilter" },
      { text: "ChatInviteLink", link: "/api/types#chatinvitelink" },
      { text: "ChatInviteLinkJoiner", link: "/api/types#chatinvitelinkjoiner" },
      { text: "ChatJoinRequest", link: "/api/types#chatjoinrequest" },
      { text: "ChatJoinType", link: "/api/types#chatjointype" },
      { text: "ChatBoostUpdated", link: "/api/types#chatboostupdated" },
      { text: "ChatSettings", link: "/api/types#chatsettings" },
      { text: "ChatShared", link: "/api/types#chatshared" },
      { text: "ChatAction", link: "/api/types#chataction" },
      { text: "ChatBackground", link: "/api/types#chatbackground" },
      { text: "Dialog", link: "/api/types#dialog" },
      { text: "Folder", link: "/api/types#folder" },
      { text: "FolderColor", link: "/api/types#foldercolor" },
      { text: "TopChatCategory", link: "/api/types#topchatcategory" },
    ],
  },
  {
    text: "User & Profile",
    collapsed: true,
    items: [
      { text: "User", link: "/api/types#user" },
      { text: "UserStatus", link: "/api/types#userstatus" },
      { text: "UserStatusUpdated", link: "/api/types#userstatusupdated" },
      { text: "UsernameInfo", link: "/api/types#usernameinfo" },
      { text: "UsersShared", link: "/api/types#usersshared" },
      { text: "ProfileColor", link: "/api/types#profilecolor" },
      { text: "ProfileTab", link: "/api/types#profiletab" },
      { text: "EmojiStatus", link: "/api/types#emojistatus" },
      { text: "Birthday", link: "/api/types#birthday" },
      { text: "BusinessConnection", link: "/api/types#businessconnection" },
      { text: "BusinessBotRights", link: "/api/types#businessbotrights" },
      { text: "BusinessIntro", link: "/api/types#businessintro" },
      { text: "BusinessRecipients", link: "/api/types#businessrecipients" },
      { text: "BusinessSchedule", link: "/api/types#businessschedule" },
      { text: "BusinessWeeklyOpen", link: "/api/types#businessweeklyopen" },
      { text: "BusinessWorkingHours", link: "/api/types#businessworkinghours" },
      { text: "ClientPlatform", link: "/api/types#clientplatform" },
      { text: "ActiveSession", link: "/api/types#activesession" },
      { text: "ActiveSessions", link: "/api/types#activesessions" },
    ],
  },
  {
    text: "Messages & Formatting",
    collapsed: true,
    items: [
      { text: "MessageEntity", link: "/api/types#messageentity" },
      { text: "MessageEntityType", link: "/api/types#messageentitytype" },
      { text: "MessageOrigin", link: "/api/types#messageorigin" },
      { text: "MessageOriginType", link: "/api/types#messageorigintype" },
      { text: "MessageMediaType", link: "/api/types#messagemediatype" },
      { text: "MessageServiceType", link: "/api/types#messageservicetype" },
      { text: "MessageReactions", link: "/api/types#messagereactions" },
      { text: "MessageReactionUpdated", link: "/api/types#messagereactionupdated" },
      { text: "MessageReactionCountUpdated", link: "/api/types#messagereactioncountupdated" },
      { text: "FormattedText", link: "/api/types#formattedtext" },
      { text: "ParseMode", link: "/api/types#parsemode" },
      { text: "TextQuote", link: "/api/types#textquote" },
      { text: "FactCheck", link: "/api/types#factcheck" },
      { text: "LinkPreviewOptions", link: "/api/types#linkpreviewoptions" },
      { text: "ForwardHeader", link: "/api/types#forwardheader" },
      { text: "ExternalReplyInfo", link: "/api/types#externalreplyinfo" },
      { text: "ReplyParameters", link: "/api/types#replyparameters" },
      { text: "ReplyColor", link: "/api/types#replycolor" },
      { text: "DeletedMessages", link: "/api/types#deletedmessages" },
      { text: "MessagesFilter", link: "/api/types#messagesfilter" },
    ],
  },
  {
    text: "Reactions & Polls",
    collapsed: true,
    items: [
      { text: "Reaction", link: "/api/types#reaction" },
      { text: "ReactionCount", link: "/api/types#reactioncount" },
      { text: "BotReactionCount", link: "/api/types#botreactioncount" },
      { text: "PaidReactionPrivacy", link: "/api/types#paidreactionprivacy" },
      { text: "PaidReactor", link: "/api/types#paidreactor" },
      { text: "PollType", link: "/api/types#polltype" },
      { text: "PollUpdate", link: "/api/types#pollupdate" },
      { text: "PollAnswer", link: "/api/types#pollanswer" },
    ],
  },
  {
    text: "Keyboards & Buttons",
    collapsed: true,
    items: [
      { text: "ReplyMarkup", link: "/api/types#replymarkup" },
      { text: "ReplyMarkupType", link: "/api/types#replymarkuptype" },
      { text: "InlineKeyboardButton", link: "/api/types#inlinekeyboardbutton" },
      { text: "KeyboardButton", link: "/api/types#keyboardbutton" },
      { text: "Button", link: "/api/types#button" },
      { text: "ButtonType", link: "/api/types#buttontype" },
      { text: "ButtonStyle", link: "/api/types#buttonstyle" },
      { text: "ForceReply", link: "/api/types#forcereply" },
      { text: "ReplyKeyboardRemove", link: "/api/types#replykeyboardremove" },
      { text: "LoginURL", link: "/api/types#loginurl" },
      { text: "KeyboardButtonPollType", link: "/api/types#keyboardbuttonpolltype" },
      { text: "KeyboardButtonRequestChat", link: "/api/types#keyboardbuttonrequestchat" },
      { text: "KeyboardButtonRequestUsers", link: "/api/types#keyboardbuttonrequestusers" },
    ],
  },
  {
    text: "Inline & Callbacks",
    collapsed: true,
    items: [
      { text: "CallbackQuery", link: "/api/types#callbackquery" },
      { text: "InlineQuery", link: "/api/types#inlinequery" },
      { text: "InlineQueryResult", link: "/api/types#inlinequeryresult" },
      { text: "ChosenInlineResult", link: "/api/types#choseninlineresult" },
      { text: "InputMessageContent", link: "/api/types#inputmessagecontent" },
      { text: "InputContentType", link: "/api/types#inputcontenttype" },
      { text: "SentWebAppMessage", link: "/api/types#sentwebappmessage" },
      { text: "WebAppData", link: "/api/types#webappdata" },
      { text: "WebAppInfo", link: "/api/types#webappinfo" },
    ],
  },
  {
    text: "Payments & Shipping",
    collapsed: true,
    items: [
      { text: "Payment", link: "/api/types#payment" },
      { text: "PaymentFormType", link: "/api/types#paymentformtype" },
      { text: "PaymentQueries", link: "/api/types#paymentqueries" },
      { text: "Invoice", link: "/api/types#invoice" },
      { text: "InvoiceType", link: "/api/types#invoicetype" },
      { text: "LabeledPrice", link: "/api/types#labeledprice" },
      { text: "ShippingAddress", link: "/api/types#shippingaddress" },
      { text: "ShippingOption", link: "/api/types#shippingoption" },
      { text: "ShippingQuery", link: "/api/types#shippingquery" },
      { text: "OrderInfo", link: "/api/types#orderinfo" },
      { text: "PreCheckoutQuery", link: "/api/types#precheckoutquery" },
      { text: "SuccessfulPayment", link: "/api/types#successfulpayment" },
      { text: "InputCredentials", link: "/api/types#inputcredentials" },
      { text: "InputInvoice", link: "/api/types#inputinvoice" },
      { text: "CredentialsType", link: "/api/types#credentialstype" },
    ],
  },
  {
    text: "Stories",
    collapsed: true,
    items: [
      { text: "Story", link: "/api/types#story" },
      { text: "StoryView", link: "/api/types#storyview" },
      { text: "StoriesPrivacyRules", link: "/api/types#storiesprivacyrules" },
    ],
  },
  {
    text: "Gifts & Giveaways",
    collapsed: true,
    items: [
      { text: "GiftType", link: "/api/types#gifttype" },
      { text: "GiftAttributeType", link: "/api/types#giftattributetype" },
      { text: "GiftUpgradePreview", link: "/api/types#giftupgradepreview" },
      { text: "GiftUpgradePrice", link: "/api/types#giftupgradeprice" },
      { text: "GiftedPremium", link: "/api/types#giftedpremium" },
      { text: "GiftedStars", link: "/api/types#giftedstars" },
      { text: "GiftAuction", link: "/api/types#giftauction" },
      { text: "GiftCollection", link: "/api/types#giftcollection" },
      { text: "GiftForResaleOrder", link: "/api/types#giftforresaleorder" },
      { text: "GiftPurchaseLimit", link: "/api/types#giftpurchaselimit" },
      { text: "GiftPurchaseOfferState", link: "/api/types#giftpurchaseofferstate" },
      { text: "UpgradedGiftAttribute", link: "/api/types#upgradedgiftattribute" },
      { text: "UpgradedGiftOrigin", link: "/api/types#upgradedgiftorigin" },
      { text: "UpgradedGiftOriginalDetails", link: "/api/types#upgradedgiftoriginaldetails" },
      { text: "UpgradedGiftPurchaseOffer", link: "/api/types#upgradedgiftpurchaseoffer" },
      { text: "UpgradedGiftValueInfo", link: "/api/types#upgradedgiftvalueinfo" },
      { text: "CheckedGiftCode", link: "/api/types#checkedgiftcode" },
      { text: "PremiumGiftCode", link: "/api/types#premiumgiftcode" },
      { text: "Giveaway", link: "/api/types#giveaway" },
      { text: "GiveawayWinners", link: "/api/types#giveawaywinners" },
      { text: "BoostInfo", link: "/api/types#boostinfo" },
      { text: "BoostsStatus", link: "/api/types#boostsstatus" },
      { text: "MyBoost", link: "/api/types#myboost" },
    ],
  },
  {
    text: "Privacy & Security",
    collapsed: true,
    items: [
      { text: "PrivacyKey", link: "/api/types#privacykey" },
      { text: "PrivacyRule", link: "/api/types#privacyrule" },
      { text: "PrivacyRuleType", link: "/api/types#privacyruletype" },
      { text: "InputPrivacyRule", link: "/api/types#inputprivacyrule" },
      { text: "InputPrivacyRuleType", link: "/api/types#inputprivacyruletype" },
      { text: "GlobalPrivacySettings", link: "/api/types#globalprivacysettings" },
      { text: "BlockList", link: "/api/types#blocklist" },
    ],
  },
  {
    text: "Auth & Sessions",
    collapsed: true,
    items: [
      { text: "SentCodeInfo", link: "/api/types#sentcodeinfo" },
      { text: "SentCodeType", link: "/api/types#sentcodetype" },
      { text: "NextCodeType", link: "/api/types#nextcodetype" },
      { text: "TermsOfService", link: "/api/types#termsofservice" },
      { text: "PhoneNumberCodeType", link: "/api/types#phonenumbercodetype" },
    ],
  },
  {
    text: "Input Types & Helpers",
    collapsed: true,
    items: [
      { text: "InputMedia", link: "/api/types#inputmedia" },
      { text: "InputMediaType", link: "/api/types#inputmediatype" },
      { text: "InputChatPhoto", link: "/api/types#inputchatphoto" },
      { text: "InputPhoto", link: "/api/types#inputphoto" },
      { text: "InputPollOption", link: "/api/types#inputpolloption" },
      { text: "InputPhoneContact", link: "/api/types#inputphonecontact" },
      { text: "MaskPosition", link: "/api/types#maskposition" },
      { text: "MaskPointType", link: "/api/types#maskpointtype" },
      { text: "StickerType", link: "/api/types#stickertype" },
      { text: "MediaArea", link: "/api/types#mediaarea" },
      { text: "MediaAreaType", link: "/api/types#mediaareatype" },
      { text: "PeerInfo", link: "/api/types#peerinfo" },
      { text: "PeerMap", link: "/api/types#peermap" },
    ],
  },
  {
    text: "Bot & Commands",
    collapsed: true,
    items: [
      { text: "BotCommand", link: "/api/types#botcommand" },
      { text: "BotCommandScope", link: "/api/types#botcommandscope" },
      { text: "BotCommandScopeType", link: "/api/types#botcommandscopetype" },
      { text: "MenuButton", link: "/api/types#menubutton" },
      { text: "MenuButtonType", link: "/api/types#menubuttontype" },
      { text: "ManagedBotUpdated", link: "/api/types#managedbotupdated" },
    ],
  },
  {
    text: "Service & System",
    collapsed: true,
    items: [
      { text: "ServiceMessage", link: "/api/types#servicemessage" },
      { text: "ServiceActionType", link: "/api/types#serviceactiontype" },
      { text: "PhoneCallDiscardReason", link: "/api/types#phonecalldiscardreason" },
      { text: "PhoneCallEnded", link: "/api/types#phonecallended" },
      { text: "PhoneCallStarted", link: "/api/types#phonecallstarted" },
      { text: "ProximityAlertTriggered", link: "/api/types#proximityalerttriggered" },
      { text: "VideoChatStarted", link: "/api/types#videochatstarted" },
      { text: "VideoChatEnded", link: "/api/types#videochatoended" },
      { text: "VideoChatScheduled", link: "/api/types#videochatscheduled" },
      { text: "VideoChatMembersInvited", link: "/api/types#videochatmembersinvited" },
      { text: "GroupCallMember", link: "/api/types#groupcallmember" },
      { text: "WriteAccessAllowed", link: "/api/types#writeaccessallowed" },
      { text: "GameHighScore", link: "/api/types#gamehighscore" },
      { text: "AvailableEffect", link: "/api/types#availableeffect" },
      { text: "ChatColor", link: "/api/types#chatcolor" },
      { text: "Restriction", link: "/api/types#restriction" },
      { text: "Settings", link: "/api/types#settings" },
      { text: "TranslatorFunc", link: "/api/types#translatorfunc" },
    ],
  },
  {
    text: "Forum & Topics",
    collapsed: true,
    items: [
      { text: "ForumTopic", link: "/api/types#forumtopic" },
      { text: "ForumTopicCreated", link: "/api/types#forumtopiccreated" },
      { text: "ForumTopicEdited", link: "/api/types#forumtopicedited" },
    ],
  },
  {
    text: "Checklists & Suggested Posts",
    collapsed: true,
    items: [
      { text: "Checklist", link: "/api/types#checklist" },
      { text: "ChecklistTask", link: "/api/types#checklisttask" },
      { text: "SuggestedPostParameters", link: "/api/types#suggestedpostparameters" },
      { text: "SuggestedPostPrice", link: "/api/types#suggestedpostprice" },
      { text: "SuggestedPostState", link: "/api/types#suggestedpoststate" },
      { text: "SuggestedPostRefundReason", link: "/api/types#suggestedpostrefundreason" },
    ],
  },
  {
    text: "Params",
    collapsed: true,
    items: [
      { text: "SendMessage", link: "/api/types#sendmessage-params" },
      { text: "EditMessage", link: "/api/types#editmessage-params" },
      { text: "CopyMessage", link: "/api/types#copymessage-params" },
      { text: "ForwardMessages", link: "/api/types#forwardmessages-params" },
      { text: "DeleteMessages", link: "/api/types#deletemessages-params" },
      { text: "PinMessage", link: "/api/types#pinmessage-params" },
      { text: "Download", link: "/api/types#download-params" },
      { text: "InlineQuery", link: "/api/types#inlinequery-params" },
      { text: "ParseMode", link: "/api/types#parsemode-params" },
      { text: "ProgressFunc", link: "/api/types#progressfunc" },
      { text: "ProgressInfo", link: "/api/types#progressinfo" },
    ],
  },
  {
    text: "Binder Interfaces",
    collapsed: true,
    items: [
      { text: "Binder", link: "/api/types#binder" },
      { text: "ChatBinder", link: "/api/types#chatbinder" },
    ],
  },
];

export const messageMethods: SidebarEntry[] = [
  { text: "msg.Reply()", link: "/api/bound#reply" },
  { text: "msg.Send()", link: "/api/bound#send" },
  { text: "msg.Edit()", link: "/api/bound#edit" },
  { text: "msg.Delete()", link: "/api/bound#delete" },
  { text: "msg.Forward()", link: "/api/bound#forward" },
  { text: "msg.Copy()", link: "/api/bound#copy" },
  { text: "msg.React()", link: "/api/bound#react" },
  { text: "msg.Pin()", link: "/api/bound#pin" },
  { text: "msg.Download()", link: "/api/bound#download" },
  { text: "msg.ReplyMedia()", link: "/api/bound#replymedia--sendmedia--answermedia" },
  { text: "msg.ReplyPhoto()", link: "/api/bound#photo" },
  { text: "msg.ReplyAudio()", link: "/api/bound#audio" },
  { text: "msg.ReplyVideo()", link: "/api/bound#video" },
  { text: "msg.ReplyDocument()", link: "/api/bound#document" },
  { text: "msg.ReplyAnimation()", link: "/api/bound#animation" },
  { text: "msg.ReplyVoice()", link: "/api/bound#voice" },
  { text: "msg.ReplyVideoNote()", link: "/api/bound#video-note" },
  { text: "msg.ReplySticker()", link: "/api/bound#sticker" },
  { text: "msg.ReplyContact()", link: "/api/bound#contact" },
  { text: "msg.ReplyLocation()", link: "/api/bound#location" },
  { text: "msg.ReplyVenue()", link: "/api/bound#venue" },
  { text: "msg.ReplyPoll()", link: "/api/bound#poll" },
  { text: "msg.ReplyDice()", link: "/api/bound#dice" },
  { text: "msg.ReplyGame()", link: "/api/bound#game" },
  { text: "msg.ReplyMediaGroup()", link: "/api/bound#media-group-album" },
  { text: "msg.ReplyChecklist()", link: "/api/bound#checklist" },
  { text: "msg.Vote()", link: "/api/bound#vote" },
  { text: "msg.GetMediaGroup()", link: "/api/bound#getmediagroup" },
  { text: "msg.CopyMediaGroup()", link: "/api/bound#copymediagroup" },
];

export const callbackMethods: SidebarEntry[] = [
  { text: "cb.Answer()", link: "/api/bound#answer--answeralert--answerurl" },
  { text: "cb.Reply()", link: "/api/bound#reply" },
  { text: "cb.EditMessage()", link: "/api/bound#editmessage--editmessagetext" },
  { text: "cb.EditCaption()", link: "/api/bound#editcaption--editmessagecaption" },
  { text: "cb.EditMedia()", link: "/api/bound#editmedia--editmessagemedia" },
  { text: "cb.EditReplyMarkup()", link: "/api/bound#editreplymarkup--editmessagereplymarkup" },
  { text: "cb.Delete()", link: "/api/bound#delete-1" },
];

export const inlineMethods: SidebarEntry[] = [
  { text: "iq.Answer()", link: "/api/bound#answer" },
  { text: "iq.AnswerArticle()", link: "/api/bound#answerarticle--answerarticles" },
  { text: "iq.AnswerPhoto()", link: "/api/bound#answerphoto--answerphotos" },
  { text: "iq.AnswerDocument()", link: "/api/bound#answerdocument--answerdocuments" },
  { text: "iq.AnswerGame()", link: "/api/bound#answergame" },
];

export const chatMethods: SidebarEntry[] = [
  { text: "chat.Archive()", link: "/api/bound-chat#archive" },
  { text: "chat.Unarchive()", link: "/api/bound-chat#unarchive" },
  { text: "chat.SetTitle()", link: "/api/bound-chat#settitle" },
  { text: "chat.SetDescription()", link: "/api/bound-chat#setdescription" },
  { text: "chat.SetPhoto()", link: "/api/bound-chat#setphoto" },
  { text: "chat.DeletePhoto()", link: "/api/bound-chat#deletephoto" },
  { text: "chat.SetUsername()", link: "/api/bound-chat#setusername" },
  { text: "chat.BanMember()", link: "/api/bound-chat#banmember" },
  { text: "chat.UnbanMember()", link: "/api/bound-chat#unbanmember" },
  { text: "chat.RestrictMember()", link: "/api/bound-chat#restrictmember" },
  { text: "chat.PromoteMember()", link: "/api/bound-chat#promotemember" },
  { text: "chat.GetMember()", link: "/api/bound-chat#getmember" },
  { text: "chat.GetMembers()", link: "/api/bound-chat#getmembers" },
  { text: "chat.Join()", link: "/api/bound-chat#join" },
  { text: "chat.Leave()", link: "/api/bound-chat#leave" },
  { text: "chat.ExportInviteLink()", link: "/api/bound-chat#exportinvitelink" },
  { text: "chat.Mute()", link: "/api/bound-chat#mute" },
  { text: "chat.Unmute()", link: "/api/bound-chat#unmute" },
  { text: "chat.SetProtectedContent()", link: "/api/bound-chat#setprotectedcontent" },
  { text: "chat.SetTTL()", link: "/api/bound-chat#setttl" },
  { text: "chat.SetPermissions()", link: "/api/bound-chat#setpermissions" },
  { text: "chat.SetSlowMode()", link: "/api/bound-chat#setslowmode" },
  { text: "chat.UnpinAll()", link: "/api/bound-chat#unpinall" },
  { text: "chat.GetChat()", link: "/api/bound-chat#getchat" },
  { text: "chat.GetEventLog()", link: "/api/bound-chat#geteventlog" },
];

export const userBoundMethods: SidebarEntry[] = [
  { text: "user.Archive()", link: "/api/bound-user#archive" },
  { text: "user.Unarchive()", link: "/api/bound-user#unarchive" },
  { text: "user.Block()", link: "/api/bound-user#block" },
  { text: "user.Unblock()", link: "/api/bound-user#unblock" },
  { text: "user.GetCommonChats()", link: "/api/bound-user#getcommonchats" },
];

export const storyBoundMethods: SidebarEntry[] = [
  { text: "story.Reply()", link: "/api/bound-story#reply" },
  { text: "story.ReplyMedia()", link: "/api/bound-story#replymedia" },
  { text: "story.ReplyPhoto()", link: "/api/bound-story#replyphoto" },
  { text: "story.ReplyAnimation()", link: "/api/bound-story#replyanimation" },
  { text: "story.ReplyAudio()", link: "/api/bound-story#replyaudio--replyvideo--replyvoice--replyvideonote--replysticker" },
  { text: "story.Forward()", link: "/api/bound-story#forward" },
  { text: "story.Copy()", link: "/api/bound-story#copy" },
  { text: "story.Delete()", link: "/api/bound-story#delete" },
  { text: "story.EditCaption()", link: "/api/bound-story#editcaption" },
  { text: "story.EditMedia()", link: "/api/bound-story#editmedia" },
  { text: "story.EditPrivacy()", link: "/api/bound-story#editprivacy" },
  { text: "story.React()", link: "/api/bound-story#react" },
  { text: "story.Download()", link: "/api/bound-story#download" },
  { text: "story.Read()", link: "/api/bound-story#read" },
];

export const giftBoundMethods: SidebarEntry[] = [
  { text: "gift.Show()", link: "/api/bound-gift#show" },
  { text: "gift.Hide()", link: "/api/bound-gift#hide" },
  { text: "gift.Convert()", link: "/api/bound-gift#convert" },
  { text: "gift.Upgrade()", link: "/api/bound-gift#upgrade" },
  { text: "gift.Transfer()", link: "/api/bound-gift#transfer" },
];

export const otherBoundMethods: SidebarEntry[] = [
  { text: "ChatJoinRequest.Approve()", link: "/api/bound-other#approve" },
  { text: "ChatJoinRequest.Decline()", link: "/api/bound-other#decline" },
  { text: "PreCheckoutQuery.Answer()", link: "/api/bound-other#answer" },
  { text: "ShippingQuery.Answer()", link: "/api/bound-other#answer-1" },
  { text: "ActiveSession.Reset()", link: "/api/bound-other#reset" },
  { text: "Folder.Delete()", link: "/api/bound-other#delete" },
  { text: "Folder.Edit()", link: "/api/bound-other#edit" },
  { text: "Folder.IncludeChat()", link: "/api/bound-other#includechat" },
  { text: "Folder.ExcludeChat()", link: "/api/bound-other#excludechat" },
  { text: "Folder.PinChat()", link: "/api/bound-other#pinchat" },
  { text: "Folder.RemoveChat()", link: "/api/bound-other#removechat" },
];

export const userMethods: SidebarEntry[] = [
  { text: "GetMe", link: "/api/users#getme" },
  { text: "GetUser", link: "/api/users#getuser" },
  { text: "GetUsers", link: "/api/users#getusers" },
  { text: "GetCommonChats", link: "/api/users#getcommonchats" },
  { text: "UpdateProfile", link: "/api/users#updateprofile" },
  { text: "SetProfilePhoto", link: "/api/users#setprofilephoto" },
  { text: "DeleteProfilePhoto", link: "/api/users#deleteprofilephoto" },
  { text: "GetProfilePhotos", link: "/api/users#getprofilephotos" },
  { text: "SetUsername", link: "/api/users#setusername" },
  { text: "SetBio", link: "/api/users#setbio" },
  { text: "BlockUser", link: "/api/users#blockuser" },
  { text: "UnblockUser", link: "/api/users#unblockuser" },
  { text: "GetBlocked", link: "/api/users#getblocked" },
  { text: "AddContact", link: "/api/users#addcontact" },
  { text: "DeleteContacts", link: "/api/users#deletecontacts" },
  { text: "GetContacts", link: "/api/users#getcontacts" },
];
